# dbt_project.yml

name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    +schema: DBT_SSIN  # Default schema for other models
    main-dbt-model:
      distinct_Cust_nationkey:
        +database: my_database  # Specific database for this model
        +schema: my_schema      # Specific schema for this model
        +materialized: table
